apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
<<<<<<< HEAD
 DB_DATABASE: cG9zdGRi
 DB_USERNAME: cG9zdHVzZXI=
 DB_PASSWORD: cG9zdHB3ZA==
 DB_HOST: cG9zdGdyZXM=
=======

 DB_USERNAME: cG9zdHVzZXI=
 DB_PASSWORD: cG9zdHB3ZA==
>>>>>>> a483bde (Alteração no Dockerfile e Subindo configurações do Grafana, Prometheus e Loki)
