apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
<<<<<<< HEAD
  selector:
    matchLabels:
      app: api
  template:
    metadata:
=======
  #replicas: 3
  selector:
  
    matchLabels:
      app: api
  template:
    
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
>>>>>>> a483bde (Alteração no Dockerfile e Subindo configurações do Grafana, Prometheus e Loki)
      labels:
        app: api  
    spec:
      containers:
      - name: api
<<<<<<< HEAD
        image: ellisonalencar/kube-news:1.0
=======
        image: ellisonalencar/kubenews:1.3
>>>>>>> a483bde (Alteração no Dockerfile e Subindo configurações do Grafana, Prometheus e Loki)
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

<<<<<<< HEAD
        envFrom:
          - secretRef:
              name: api-secret
=======
        env:
          - name: DB_DATABASE
            value: postgres
          - name: DB_HOST
            value: db-service

          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: DB_USERNAME
                name: api-secret    
          
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: api-secret 
        
        

      
>>>>>>> a483bde (Alteração no Dockerfile e Subindo configurações do Grafana, Prometheus e Loki)

