apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
<<<<<<< HEAD
=======
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8082"
>>>>>>> a483bde (Alteração no Dockerfile e Subindo configurações do Grafana, Prometheus e Loki)
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:6.15
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
<<<<<<< HEAD
        - containerPort: 80
=======
        - containerPort: 8082
>>>>>>> a483bde (Alteração no Dockerfile e Subindo configurações do Grafana, Prometheus e Loki)
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: ellison@teste.com
          - name: PGADMIN_DEFAULT_PASSWORD
            value: pgpwd
