name: CI-CD

on: 
  push:
    branches: ["hmg"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.0.1
      
      - name: Autenticação docker hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
        
        
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Docker
          file: ./Docker/Dockerfile
          push: true
          tags:
            ellisonalencar/kube-news:${{github.run.number}} ,
            ellisonalencar/kube-news:latest


  
  
  
