name: CI-CD

on: 
  push:
    branches: ["main"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.0.1
      
      - name: Autenticação docker hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
        
        
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            ellisonalencar/kube-news:${{github.run.number}}
            ellisonalencar/kube-news:latest


  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.0.1
      
      - name: Definindo o context
        uses: Azure/k8s-set-context@v3.0
        with: 
            method: kubconfig
            kubeconfig: ${{secrets.k8s_config}}
        
  
  
